### Product Index Action
GET http://localhost:3000/products.json


### Product Show Action
GET http://localhost:3000/products/3.json


### Product Create Action
POST http://localhost:3000/products.json
Content-Type: application/json 

{
  "name": "test name",
  "price": 5,
  "image_url": "test url",
  "description": "test description",
  "inventory": 2
}


### Product Update Action
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "price": 10000,
  "inventory": 1
}


### Product Delete Action
DELETE http://localhost:3000/products/6.json
