### Product Index Action
GET http://localhost:3000/products


### Product Show Action
GET http://localhost:3000/products/3


### Product Create Action
POST http://localhost:3000/products.json
Content-Type: application/json 

  {
  "name": "test name",
  "price": "0",
  "image_url": "test url",
  "description": "test description"
  }


### Product Update Action
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "image_url": "https://tenor.com/view/dancing-cockroach-meme-roach-spinning-gif-15776567"
}


### Product Delete Action
DELETE http://localhost:3000/products/6.json
