### Product Index Action
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json 

###
#GET http://localhost:3000/products/images.json


### Product Show Action
GET http://localhost:3000/products/1.json


### Product Create Action
POST http://localhost:3000/products.json
Content-Type: application/json 

{
  "name": "test name",
  "price": 5,
  "description": "test description",
  "inventory": 2
  
}


### Product Update Action
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "image_id": 5
}


### Product Delete Action
DELETE http://localhost:3000/products/6.json


### Users index
GET http://localhost:3000/users.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test4@test.com",
  "password": "password",
  "password_confirmation": "password"
}
